In [1]:
from assets import models
import pandas as pd

from assets.database import db_session

In [3]:
df= pd.read_csv('assets/data.csv')

In [4]:
df.head()

        date  subscribers  reviews
0  2019/1/17         2671      194
1  2019/1/18         2671      195
2  2019/1/19         2674      197
3  2019/1/20         2685      199
4  2019/1/21         2695      199

In [5]:
df.iloc[0,0]

'2019/1/17'

In [6]:
import datetime

In [9]:
date=datetime.datetime.strptime(df.iloc[0,0],'%Y/%m/%d').date()
date

datetime.date(2019, 1, 17)

In [13]:
for index,_df in df.iterrows():
    date=datetime.datetime.strptime(_df['date'],'%Y/%m/%d').date()
    row=models.Data(date=date,subscribers=_df['subscribers'],reviews=_df['reviews'])
    db_session.add(row)
db_session.commit()

2020-12-02 18:07:03,066 INFO sqlalchemy.engine.base.Engine SELECT CAST('test plain returns' AS VARCHAR(60)) AS anon_1
2020-12-02 18:07:03,066 INFO sqlalchemy.engine.base.Engine ()
2020-12-02 18:07:03,067 INFO sqlalchemy.engine.base.Engine SELECT CAST('test unicode returns' AS VARCHAR(60)) AS anon_1
2020-12-02 18:07:03,067 INFO sqlalchemy.engine.base.Engine ()
2020-12-02 18:07:03,068 INFO sqlalchemy.engine.base.Engine BEGIN (implicit)
2020-12-02 18:07:03,073 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,073 INFO sqlalchemy.engine.base.Engine ('2019-01-17', 2671, 194, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,075 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,076 INFO sqlalchemy.engine.base.Engine ('2019-01-18', 2671, 195, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,077 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,077 INFO sqlalchemy.engine.base.Engine ('2019-01-19', 2674, 197, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,078 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,079 INFO sqlalchemy.engine.base.Engine ('2019-01-20', 2685, 199, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,079 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,080 INFO sqlalchemy.engine.base.Engine ('2019-01-21', 2695, 199, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,080 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,081 INFO sqlalchemy.engine.base.Engine ('2019-01-22', 2701, 200, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,082 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,082 INFO sqlalchemy.engine.base.Engine ('2019-01-23', 2710, 200, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,083 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,083 INFO sqlalchemy.engine.base.Engine ('2019-01-24', 2718, 201, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,084 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,085 INFO sqlalchemy.engine.base.Engine ('2019-01-25', 2722, 201, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,085 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,086 INFO sqlalchemy.engine.base.Engine ('2019-01-26', 2725, 201, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,087 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,087 INFO sqlalchemy.engine.base.Engine ('2019-01-27', 2734, 202, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,088 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,089 INFO sqlalchemy.engine.base.Engine ('2019-01-28', 2753, 204, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,089 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,090 INFO sqlalchemy.engine.base.Engine ('2019-01-29', 2773, 206, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,091 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,091 INFO sqlalchemy.engine.base.Engine ('2019-01-30', 2785, 208, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,093 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,093 INFO sqlalchemy.engine.base.Engine ('2019-01-31', 2803, 210, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,094 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,095 INFO sqlalchemy.engine.base.Engine ('2019-02-01', 2845, 211, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,096 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,096 INFO sqlalchemy.engine.base.Engine ('2019-02-02', 2847, 213, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,097 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,097 INFO sqlalchemy.engine.base.Engine ('2019-02-03', 2847, 213, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,098 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,099 INFO sqlalchemy.engine.base.Engine ('2019-02-04', 2851, 217, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,099 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,100 INFO sqlalchemy.engine.base.Engine ('2019-02-05', 2852, 218, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,101 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,101 INFO sqlalchemy.engine.base.Engine ('2019-02-06', 2857, 219, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,102 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,102 INFO sqlalchemy.engine.base.Engine ('2019-02-07', 2861, 220, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,103 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,103 INFO sqlalchemy.engine.base.Engine ('2019-02-08', 2865, 222, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,104 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,105 INFO sqlalchemy.engine.base.Engine ('2019-02-09', 2870, 224, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,105 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,106 INFO sqlalchemy.engine.base.Engine ('2019-02-10', 2875, 224, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,107 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,107 INFO sqlalchemy.engine.base.Engine ('2019-02-11', 2892, 227, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,108 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,109 INFO sqlalchemy.engine.base.Engine ('2019-02-12', 2906, 229, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,110 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,111 INFO sqlalchemy.engine.base.Engine ('2019-02-13', 2919, 229, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,111 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,112 INFO sqlalchemy.engine.base.Engine ('2019-02-14', 2942, 231, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,113 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,114 INFO sqlalchemy.engine.base.Engine ('2019-02-15', 2974, 232, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,115 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,116 INFO sqlalchemy.engine.base.Engine ('2019-02-16', 2977, 234, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,117 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,117 INFO sqlalchemy.engine.base.Engine ('2019-02-17', 2978, 234, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,118 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,119 INFO sqlalchemy.engine.base.Engine ('2019-02-18', 2981, 234, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,119 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,120 INFO sqlalchemy.engine.base.Engine ('2019-02-19', 2983, 234, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,121 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,122 INFO sqlalchemy.engine.base.Engine ('2019-02-20', 2984, 237, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,122 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,123 INFO sqlalchemy.engine.base.Engine ('2019-02-21', 2987, 239, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,124 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,124 INFO sqlalchemy.engine.base.Engine ('2019-02-22', 2989, 239, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,126 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,126 INFO sqlalchemy.engine.base.Engine ('2019-02-23', 2993, 241, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,128 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,128 INFO sqlalchemy.engine.base.Engine ('2019-02-24', 2995, 241, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,129 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,130 INFO sqlalchemy.engine.base.Engine ('2019-02-25', 3009, 241, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,130 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,131 INFO sqlalchemy.engine.base.Engine ('2019-02-26', 3014, 243, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,131 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,132 INFO sqlalchemy.engine.base.Engine ('2019-02-27', 3023, 243, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,133 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,133 INFO sqlalchemy.engine.base.Engine ('2019-02-28', 3031, 243, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,134 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,134 INFO sqlalchemy.engine.base.Engine ('2019-03-01', 3052, 244, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,135 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,136 INFO sqlalchemy.engine.base.Engine ('2019-03-02', 3060, 245, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,136 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,137 INFO sqlalchemy.engine.base.Engine ('2019-03-03', 3062, 246, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,138 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,138 INFO sqlalchemy.engine.base.Engine ('2019-03-04', 3063, 249, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,139 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,140 INFO sqlalchemy.engine.base.Engine ('2019-03-05', 3066, 252, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,140 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,141 INFO sqlalchemy.engine.base.Engine ('2019-03-06', 3071, 254, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,142 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,143 INFO sqlalchemy.engine.base.Engine ('2019-03-07', 3074, 255, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,143 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,144 INFO sqlalchemy.engine.base.Engine ('2019-03-08', 3076, 256, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,145 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,145 INFO sqlalchemy.engine.base.Engine ('2019-03-09', 3077, 258, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,146 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,147 INFO sqlalchemy.engine.base.Engine ('2019-03-10', 3080, 258, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,148 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,148 INFO sqlalchemy.engine.base.Engine ('2019-03-11', 3087, 261, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,149 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,150 INFO sqlalchemy.engine.base.Engine ('2019-03-12', 3089, 261, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,151 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,151 INFO sqlalchemy.engine.base.Engine ('2019-03-13', 3093, 262, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,152 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,153 INFO sqlalchemy.engine.base.Engine ('2019-03-14', 3098, 262, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,154 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,154 INFO sqlalchemy.engine.base.Engine ('2019-03-15', 3104, 262, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,155 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,156 INFO sqlalchemy.engine.base.Engine ('2019-03-16', 3112, 262, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,156 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,157 INFO sqlalchemy.engine.base.Engine ('2019-03-17', 3120, 262, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,158 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,159 INFO sqlalchemy.engine.base.Engine ('2019-03-18', 3131, 265, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,160 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,160 INFO sqlalchemy.engine.base.Engine ('2019-03-19', 3142, 266, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,161 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,162 INFO sqlalchemy.engine.base.Engine ('2019-03-20', 3162, 266, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,164 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,164 INFO sqlalchemy.engine.base.Engine ('2019-03-21', 3173, 268, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,165 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,166 INFO sqlalchemy.engine.base.Engine ('2019-03-22', 3180, 269, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,167 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,168 INFO sqlalchemy.engine.base.Engine ('2019-03-23', 3187, 271, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,169 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,170 INFO sqlalchemy.engine.base.Engine ('2019-03-24', 3189, 271, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,171 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,172 INFO sqlalchemy.engine.base.Engine ('2019-03-25', 3196, 274, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,172 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,173 INFO sqlalchemy.engine.base.Engine ('2019-03-26', 3212, 274, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,174 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,174 INFO sqlalchemy.engine.base.Engine ('2019-03-27', 3220, 274, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,175 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,176 INFO sqlalchemy.engine.base.Engine ('2019-03-28', 3226, 275, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,176 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,177 INFO sqlalchemy.engine.base.Engine ('2019-03-29', 3241, 275, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,178 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,178 INFO sqlalchemy.engine.base.Engine ('2019-03-30', 3253, 278, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,179 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,180 INFO sqlalchemy.engine.base.Engine ('2019-03-31', 3255, 278, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,180 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,181 INFO sqlalchemy.engine.base.Engine ('2019-04-01', 3258, 280, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,182 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,182 INFO sqlalchemy.engine.base.Engine ('2019-04-02', 3262, 282, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,183 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,184 INFO sqlalchemy.engine.base.Engine ('2019-04-03', 3264, 282, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,184 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,185 INFO sqlalchemy.engine.base.Engine ('2019-04-04', 3272, 282, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,185 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,186 INFO sqlalchemy.engine.base.Engine ('2019-04-05', 3275, 284, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,187 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,187 INFO sqlalchemy.engine.base.Engine ('2019-04-06', 3276, 287, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,188 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,189 INFO sqlalchemy.engine.base.Engine ('2019-04-07', 3279, 289, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,189 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,190 INFO sqlalchemy.engine.base.Engine ('2019-04-08', 3285, 289, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,191 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,191 INFO sqlalchemy.engine.base.Engine ('2019-04-09', 3300, 291, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,192 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,192 INFO sqlalchemy.engine.base.Engine ('2019-04-10', 3306, 293, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,193 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,194 INFO sqlalchemy.engine.base.Engine ('2019-04-11', 3312, 295, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,195 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,196 INFO sqlalchemy.engine.base.Engine ('2019-04-12', 3319, 295, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,197 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,198 INFO sqlalchemy.engine.base.Engine ('2019-04-13', 3324, 295, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,200 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,202 INFO sqlalchemy.engine.base.Engine ('2019-04-14', 3325, 297, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,203 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,203 INFO sqlalchemy.engine.base.Engine ('2019-04-15', 3329, 298, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,205 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,206 INFO sqlalchemy.engine.base.Engine ('2019-04-16', 3331, 299, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,208 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,210 INFO sqlalchemy.engine.base.Engine ('2019-04-17', 3332, 299, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,212 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,213 INFO sqlalchemy.engine.base.Engine ('2019-04-18', 3333, 299, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,214 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,215 INFO sqlalchemy.engine.base.Engine ('2019-04-19', 3336, 299, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,217 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,217 INFO sqlalchemy.engine.base.Engine ('2019-04-20', 3339, 299, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,218 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,219 INFO sqlalchemy.engine.base.Engine ('2019-04-21', 3343, 300, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,220 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,221 INFO sqlalchemy.engine.base.Engine ('2019-04-22', 3349, 302, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,222 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,223 INFO sqlalchemy.engine.base.Engine ('2019-04-23', 3357, 303, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,225 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,225 INFO sqlalchemy.engine.base.Engine ('2019-04-24', 3370, 303, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,226 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,227 INFO sqlalchemy.engine.base.Engine ('2019-04-25', 3388, 304, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,228 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,229 INFO sqlalchemy.engine.base.Engine ('2019-04-26', 3412, 304, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,229 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,230 INFO sqlalchemy.engine.base.Engine ('2019-04-27', 3437, 305, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,231 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,232 INFO sqlalchemy.engine.base.Engine ('2019-04-28', 3439, 305, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,233 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,233 INFO sqlalchemy.engine.base.Engine ('2019-04-29', 3440, 308, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,234 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,235 INFO sqlalchemy.engine.base.Engine ('2019-04-30', 3447, 309, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,236 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,236 INFO sqlalchemy.engine.base.Engine ('2019-05-01', 3466, 310, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,237 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,238 INFO sqlalchemy.engine.base.Engine ('2019-05-02', 3481, 311, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,239 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,239 INFO sqlalchemy.engine.base.Engine ('2019-05-03', 3504, 314, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,240 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,241 INFO sqlalchemy.engine.base.Engine ('2019-05-04', 3522, 317, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,242 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,242 INFO sqlalchemy.engine.base.Engine ('2019-05-05', 3527, 322, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,244 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,244 INFO sqlalchemy.engine.base.Engine ('2019-05-06', 3533, 324, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,246 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,246 INFO sqlalchemy.engine.base.Engine ('2019-05-07', 3543, 327, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,247 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,248 INFO sqlalchemy.engine.base.Engine ('2019-05-08', 3546, 328, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,249 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,249 INFO sqlalchemy.engine.base.Engine ('2019-05-09', 3555, 330, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,250 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,251 INFO sqlalchemy.engine.base.Engine ('2019-05-10', 3566, 332, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,251 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,252 INFO sqlalchemy.engine.base.Engine ('2019-05-11', 3583, 334, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,253 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,253 INFO sqlalchemy.engine.base.Engine ('2019-05-12', 3594, 335, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,254 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,254 INFO sqlalchemy.engine.base.Engine ('2019-05-13', 3614, 338, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,255 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,256 INFO sqlalchemy.engine.base.Engine ('2019-05-14', 3633, 340, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,257 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,257 INFO sqlalchemy.engine.base.Engine ('2019-05-15', 3647, 344, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,258 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,259 INFO sqlalchemy.engine.base.Engine ('2019-05-16', 3648, 349, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,260 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,261 INFO sqlalchemy.engine.base.Engine ('2019-05-17', 3649, 349, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,262 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,262 INFO sqlalchemy.engine.base.Engine ('2019-05-18', 3651, 351, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,264 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,264 INFO sqlalchemy.engine.base.Engine ('2019-05-19', 3654, 351, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,265 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,266 INFO sqlalchemy.engine.base.Engine ('2019-05-20', 3658, 354, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,267 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,267 INFO sqlalchemy.engine.base.Engine ('2019-05-21', 3671, 354, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,268 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,269 INFO sqlalchemy.engine.base.Engine ('2019-05-22', 3675, 359, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,270 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,270 INFO sqlalchemy.engine.base.Engine ('2019-05-23', 3681, 359, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,271 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,272 INFO sqlalchemy.engine.base.Engine ('2019-05-24', 3694, 361, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,273 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,273 INFO sqlalchemy.engine.base.Engine ('2019-05-25', 3699, 361, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,274 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,275 INFO sqlalchemy.engine.base.Engine ('2019-05-26', 3711, 364, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,276 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,277 INFO sqlalchemy.engine.base.Engine ('2019-05-27', 3722, 368, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,278 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,278 INFO sqlalchemy.engine.base.Engine ('2019-05-28', 3734, 373, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,279 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,280 INFO sqlalchemy.engine.base.Engine ('2019-05-29', 3766, 374, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,280 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,281 INFO sqlalchemy.engine.base.Engine ('2019-05-30', 3781, 375, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,282 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,282 INFO sqlalchemy.engine.base.Engine ('2019-05-31', 3784, 375, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,283 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,284 INFO sqlalchemy.engine.base.Engine ('2019-06-01', 3789, 378, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,285 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,285 INFO sqlalchemy.engine.base.Engine ('2019-06-02', 3790, 379, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,286 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,287 INFO sqlalchemy.engine.base.Engine ('2019-06-03', 3793, 380, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,288 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,288 INFO sqlalchemy.engine.base.Engine ('2019-06-04', 3795, 383, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,289 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,290 INFO sqlalchemy.engine.base.Engine ('2019-06-05', 3808, 385, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,291 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,291 INFO sqlalchemy.engine.base.Engine ('2019-06-06', 3830, 386, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,292 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,293 INFO sqlalchemy.engine.base.Engine ('2019-06-07', 3843, 387, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,294 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,295 INFO sqlalchemy.engine.base.Engine ('2019-06-08', 3857, 390, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,296 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,296 INFO sqlalchemy.engine.base.Engine ('2019-06-09', 3870, 394, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,297 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,298 INFO sqlalchemy.engine.base.Engine ('2019-06-10', 3895, 395, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,299 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,299 INFO sqlalchemy.engine.base.Engine ('2019-06-11', 3919, 397, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,300 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,300 INFO sqlalchemy.engine.base.Engine ('2019-06-12', 3942, 399, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,301 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,302 INFO sqlalchemy.engine.base.Engine ('2019-06-13', 3983, 402, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,302 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,303 INFO sqlalchemy.engine.base.Engine ('2019-06-14', 4022, 404, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,303 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,304 INFO sqlalchemy.engine.base.Engine ('2019-06-15', 4053, 409, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,305 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,305 INFO sqlalchemy.engine.base.Engine ('2019-06-16', 4058, 410, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,306 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,306 INFO sqlalchemy.engine.base.Engine ('2019-06-17', 4063, 414, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,307 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,308 INFO sqlalchemy.engine.base.Engine ('2019-06-18', 4064, 417, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,309 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,309 INFO sqlalchemy.engine.base.Engine ('2019-06-19', 4065, 422, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,310 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,311 INFO sqlalchemy.engine.base.Engine ('2019-06-20', 4066, 424, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,312 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,312 INFO sqlalchemy.engine.base.Engine ('2019-06-21', 4069, 425, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,313 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,314 INFO sqlalchemy.engine.base.Engine ('2019-06-22', 4070, 426, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,314 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,315 INFO sqlalchemy.engine.base.Engine ('2019-06-23', 4073, 427, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,316 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,316 INFO sqlalchemy.engine.base.Engine ('2019-06-24', 4084, 427, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,317 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,317 INFO sqlalchemy.engine.base.Engine ('2019-06-25', 4108, 427, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,318 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,319 INFO sqlalchemy.engine.base.Engine ('2019-06-26', 4122, 433, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,319 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,320 INFO sqlalchemy.engine.base.Engine ('2019-06-27', 4132, 436, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,321 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,321 INFO sqlalchemy.engine.base.Engine ('2019-06-28', 4150, 440, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,322 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,322 INFO sqlalchemy.engine.base.Engine ('2019-06-29', 4162, 440, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,323 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,323 INFO sqlalchemy.engine.base.Engine ('2019-06-30', 4164, 446, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,324 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,325 INFO sqlalchemy.engine.base.Engine ('2019-07-01', 4167, 448, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,326 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,326 INFO sqlalchemy.engine.base.Engine ('2019-07-02', 4174, 450, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,327 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,328 INFO sqlalchemy.engine.base.Engine ('2019-07-03', 4179, 455, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,329 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,329 INFO sqlalchemy.engine.base.Engine ('2019-07-04', 4187, 456, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,330 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,331 INFO sqlalchemy.engine.base.Engine ('2019-07-05', 4200, 456, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,331 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,332 INFO sqlalchemy.engine.base.Engine ('2019-07-06', 4210, 458, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,333 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,333 INFO sqlalchemy.engine.base.Engine ('2019-07-07', 4211, 458, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,334 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,334 INFO sqlalchemy.engine.base.Engine ('2019-07-08', 4214, 464, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,335 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,335 INFO sqlalchemy.engine.base.Engine ('2019-07-09', 4219, 464, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,336 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,337 INFO sqlalchemy.engine.base.Engine ('2019-07-10', 4223, 468, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,337 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,338 INFO sqlalchemy.engine.base.Engine ('2019-07-11', 4228, 469, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,339 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,339 INFO sqlalchemy.engine.base.Engine ('2019-07-12', 4236, 469, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,340 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,340 INFO sqlalchemy.engine.base.Engine ('2019-07-13', 4239, 471, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,341 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,342 INFO sqlalchemy.engine.base.Engine ('2019-07-14', 4243, 471, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,343 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,344 INFO sqlalchemy.engine.base.Engine ('2019-07-15', 4250, 473, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,344 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,345 INFO sqlalchemy.engine.base.Engine ('2019-07-16', 4265, 476, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,346 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,346 INFO sqlalchemy.engine.base.Engine ('2019-07-17', 4288, 476, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,347 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,348 INFO sqlalchemy.engine.base.Engine ('2019-07-18', 4313, 483, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,349 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,349 INFO sqlalchemy.engine.base.Engine ('2019-07-19', 4329, 483, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,350 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,350 INFO sqlalchemy.engine.base.Engine ('2019-07-20', 4329, 486, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,351 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,352 INFO sqlalchemy.engine.base.Engine ('2019-07-21', 4329, 487, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,352 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,353 INFO sqlalchemy.engine.base.Engine ('2019-07-22', 4333, 492, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,354 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,354 INFO sqlalchemy.engine.base.Engine ('2019-07-23', 4335, 493, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,355 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,355 INFO sqlalchemy.engine.base.Engine ('2019-07-24', 4353, 494, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,356 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,356 INFO sqlalchemy.engine.base.Engine ('2019-07-25', 4370, 496, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,357 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,358 INFO sqlalchemy.engine.base.Engine ('2019-07-26', 4397, 500, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,359 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,359 INFO sqlalchemy.engine.base.Engine ('2019-07-27', 4419, 504, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,360 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,361 INFO sqlalchemy.engine.base.Engine ('2019-07-28', 4422, 507, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,362 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,362 INFO sqlalchemy.engine.base.Engine ('2019-07-29', 4423, 513, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,363 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,364 INFO sqlalchemy.engine.base.Engine ('2019-07-30', 4425, 516, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,364 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,365 INFO sqlalchemy.engine.base.Engine ('2019-07-31', 4427, 518, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,366 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,366 INFO sqlalchemy.engine.base.Engine ('2019-08-01', 4432, 519, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,367 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,368 INFO sqlalchemy.engine.base.Engine ('2019-08-02', 4433, 520, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,368 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,369 INFO sqlalchemy.engine.base.Engine ('2019-08-03', 4435, 522, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,370 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,370 INFO sqlalchemy.engine.base.Engine ('2019-08-04', 4437, 522, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,371 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,371 INFO sqlalchemy.engine.base.Engine ('2019-08-05', 4440, 526, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,372 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,373 INFO sqlalchemy.engine.base.Engine ('2019-08-06', 4444, 528, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,373 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,374 INFO sqlalchemy.engine.base.Engine ('2019-08-07', 4452, 528, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,375 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,375 INFO sqlalchemy.engine.base.Engine ('2019-08-08', 4466, 529, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,376 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,377 INFO sqlalchemy.engine.base.Engine ('2019-08-09', 4493, 529, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,378 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,378 INFO sqlalchemy.engine.base.Engine ('2019-08-10', 4521, 530, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,379 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,380 INFO sqlalchemy.engine.base.Engine ('2019-08-11', 4528, 531, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,380 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,381 INFO sqlalchemy.engine.base.Engine ('2019-08-12', 4529, 533, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,381 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,382 INFO sqlalchemy.engine.base.Engine ('2019-08-13', 4532, 534, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,383 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,383 INFO sqlalchemy.engine.base.Engine ('2019-08-14', 4534, 537, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,384 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,384 INFO sqlalchemy.engine.base.Engine ('2019-08-15', 4535, 537, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,385 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,385 INFO sqlalchemy.engine.base.Engine ('2019-08-16', 4539, 539, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,386 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,387 INFO sqlalchemy.engine.base.Engine ('2019-08-17', 4539, 540, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,429 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,429 INFO sqlalchemy.engine.base.Engine ('2019-08-18', 4541, 541, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,430 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,430 INFO sqlalchemy.engine.base.Engine ('2019-08-19', 4545, 544, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,431 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,431 INFO sqlalchemy.engine.base.Engine ('2019-08-20', 4545, 545, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,432 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,432 INFO sqlalchemy.engine.base.Engine ('2019-08-21', 4561, 548, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,433 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,433 INFO sqlalchemy.engine.base.Engine ('2019-08-22', 4590, 549, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,434 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,434 INFO sqlalchemy.engine.base.Engine ('2019-08-23', 4624, 549, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,435 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,435 INFO sqlalchemy.engine.base.Engine ('2019-08-24', 4641, 552, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,436 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,436 INFO sqlalchemy.engine.base.Engine ('2019-08-25', 4665, 554, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,437 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,437 INFO sqlalchemy.engine.base.Engine ('2019-08-26', 4702, 557, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,438 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,438 INFO sqlalchemy.engine.base.Engine ('2019-08-27', 4730, 561, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,438 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,439 INFO sqlalchemy.engine.base.Engine ('2019-08-28', 4761, 564, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,439 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,440 INFO sqlalchemy.engine.base.Engine ('2019-08-29', 4793, 566, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,440 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,440 INFO sqlalchemy.engine.base.Engine ('2019-08-30', 4846, 566, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,441 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,442 INFO sqlalchemy.engine.base.Engine ('2019-08-31', 4878, 571, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,443 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,444 INFO sqlalchemy.engine.base.Engine ('2019-09-01', 4884, 572, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,445 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,445 INFO sqlalchemy.engine.base.Engine ('2019-09-02', 4888, 573, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,446 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,446 INFO sqlalchemy.engine.base.Engine ('2019-09-03', 4887, 574, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,447 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,447 INFO sqlalchemy.engine.base.Engine ('2019-09-04', 4888, 575, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,448 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,449 INFO sqlalchemy.engine.base.Engine ('2019-09-05', 4890, 577, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,449 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,450 INFO sqlalchemy.engine.base.Engine ('2019-09-06', 4892, 577, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,450 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,451 INFO sqlalchemy.engine.base.Engine ('2019-09-07', 4894, 578, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,451 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,452 INFO sqlalchemy.engine.base.Engine ('2019-09-08', 4896, 578, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,452 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,452 INFO sqlalchemy.engine.base.Engine ('2019-09-09', 4907, 579, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,453 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,453 INFO sqlalchemy.engine.base.Engine ('2019-09-10', 4918, 581, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,454 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,454 INFO sqlalchemy.engine.base.Engine ('2019-09-11', 4935, 583, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,455 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,456 INFO sqlalchemy.engine.base.Engine ('2019-09-12', 4949, 583, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,456 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,457 INFO sqlalchemy.engine.base.Engine ('2019-09-13', 4965, 584, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,457 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,457 INFO sqlalchemy.engine.base.Engine ('2019-09-14', 4966, 587, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,458 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,458 INFO sqlalchemy.engine.base.Engine ('2019-09-15', 4966, 587, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,459 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,460 INFO sqlalchemy.engine.base.Engine ('2019-09-16', 4970, 590, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,460 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,461 INFO sqlalchemy.engine.base.Engine ('2019-09-17', 4972, 590, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,462 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,462 INFO sqlalchemy.engine.base.Engine ('2019-09-18', 4974, 592, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,463 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,463 INFO sqlalchemy.engine.base.Engine ('2019-09-19', 4996, 596, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,464 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,464 INFO sqlalchemy.engine.base.Engine ('2019-09-20', 4998, 601, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,465 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,465 INFO sqlalchemy.engine.base.Engine ('2019-09-21', 5001, 601, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,465 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,466 INFO sqlalchemy.engine.base.Engine ('2019-09-22', 5004, 603, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,466 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,467 INFO sqlalchemy.engine.base.Engine ('2019-09-23', 5005, 605, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,467 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,468 INFO sqlalchemy.engine.base.Engine ('2019-09-24', 5012, 605, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,468 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,469 INFO sqlalchemy.engine.base.Engine ('2019-09-25', 5023, 609, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,469 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,470 INFO sqlalchemy.engine.base.Engine ('2019-09-26', 5033, 609, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,470 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,471 INFO sqlalchemy.engine.base.Engine ('2019-09-27', 5068, 612, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,471 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,472 INFO sqlalchemy.engine.base.Engine ('2019-09-28', 5084, 613, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,472 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,472 INFO sqlalchemy.engine.base.Engine ('2019-09-29', 5088, 614, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,473 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,473 INFO sqlalchemy.engine.base.Engine ('2019-09-30', 5097, 615, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,474 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,474 INFO sqlalchemy.engine.base.Engine ('2019-10-01', 5113, 617, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,475 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,475 INFO sqlalchemy.engine.base.Engine ('2019-10-02', 5117, 618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,476 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,477 INFO sqlalchemy.engine.base.Engine ('2019-10-03', 5120, 620, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,477 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,478 INFO sqlalchemy.engine.base.Engine ('2019-10-04', 5128, 622, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,478 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,479 INFO sqlalchemy.engine.base.Engine ('2019-10-05', 5133, 624, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,479 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,480 INFO sqlalchemy.engine.base.Engine ('2019-10-06', 5137, 628, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,480 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,481 INFO sqlalchemy.engine.base.Engine ('2019-10-07', 5144, 630, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,481 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,482 INFO sqlalchemy.engine.base.Engine ('2019-10-08', 5160, 633, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,482 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,483 INFO sqlalchemy.engine.base.Engine ('2019-10-09', 5166, 637, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,483 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,484 INFO sqlalchemy.engine.base.Engine ('2019-10-10', 5167, 639, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,484 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,485 INFO sqlalchemy.engine.base.Engine ('2019-10-11', 5168, 641, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,485 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,485 INFO sqlalchemy.engine.base.Engine ('2019-10-12', 5169, 644, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,486 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,486 INFO sqlalchemy.engine.base.Engine ('2019-10-13', 5170, 646, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,487 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,487 INFO sqlalchemy.engine.base.Engine ('2019-10-14', 5170, 649, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,488 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,488 INFO sqlalchemy.engine.base.Engine ('2019-10-15', 5179, 651, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,489 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,489 INFO sqlalchemy.engine.base.Engine ('2019-10-16', 5185, 651, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,490 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,490 INFO sqlalchemy.engine.base.Engine ('2019-10-17', 5187, 652, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,490 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,491 INFO sqlalchemy.engine.base.Engine ('2019-10-18', 5189, 653, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,492 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,492 INFO sqlalchemy.engine.base.Engine ('2019-10-19', 5191, 654, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,493 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,493 INFO sqlalchemy.engine.base.Engine ('2019-10-20', 5193, 655, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,494 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,495 INFO sqlalchemy.engine.base.Engine ('2019-10-21', 5194, 656, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,495 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,496 INFO sqlalchemy.engine.base.Engine ('2019-10-22', 5197, 658, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,496 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,497 INFO sqlalchemy.engine.base.Engine ('2019-10-23', 5210, 659, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,497 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,498 INFO sqlalchemy.engine.base.Engine ('2019-10-24', 5223, 663, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,498 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,498 INFO sqlalchemy.engine.base.Engine ('2019-10-25', 5232, 663, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,499 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,499 INFO sqlalchemy.engine.base.Engine ('2019-10-26', 5233, 664, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,500 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,500 INFO sqlalchemy.engine.base.Engine ('2019-10-27', 5234, 665, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,501 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,501 INFO sqlalchemy.engine.base.Engine ('2019-10-28', 5236, 666, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,502 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,502 INFO sqlalchemy.engine.base.Engine ('2019-10-29', 5240, 670, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,503 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,503 INFO sqlalchemy.engine.base.Engine ('2019-10-30', 5242, 671, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,504 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,504 INFO sqlalchemy.engine.base.Engine ('2019-10-31', 5243, 671, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,505 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,505 INFO sqlalchemy.engine.base.Engine ('2019-11-01', 5244, 674, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,506 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,506 INFO sqlalchemy.engine.base.Engine ('2019-11-02', 5246, 674, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,507 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,507 INFO sqlalchemy.engine.base.Engine ('2019-11-03', 5246, 676, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,508 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,508 INFO sqlalchemy.engine.base.Engine ('2019-11-04', 5247, 676, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,509 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,510 INFO sqlalchemy.engine.base.Engine ('2019-11-06', 5269, 679, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,511 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,511 INFO sqlalchemy.engine.base.Engine ('2019-11-07', 5284, 681, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,512 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,512 INFO sqlalchemy.engine.base.Engine ('2019-11-08', 5298, 683, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,513 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,513 INFO sqlalchemy.engine.base.Engine ('2019-11-09', 5307, 684, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,514 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,514 INFO sqlalchemy.engine.base.Engine ('2019-11-10', 5313, 687, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,515 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,515 INFO sqlalchemy.engine.base.Engine ('2019-11-11', 5314, 687, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,516 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,516 INFO sqlalchemy.engine.base.Engine ('2019-11-12', 5314, 688, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,517 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,517 INFO sqlalchemy.engine.base.Engine ('2019-11-13', 5316, 689, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,518 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,518 INFO sqlalchemy.engine.base.Engine ('2019-11-14', 5326, 691, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,519 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,519 INFO sqlalchemy.engine.base.Engine ('2019-11-15', 5337, 691, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,520 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,520 INFO sqlalchemy.engine.base.Engine ('2019-11-16', 5338, 692, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,521 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,521 INFO sqlalchemy.engine.base.Engine ('2019-11-17', 5342, 692, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,522 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,522 INFO sqlalchemy.engine.base.Engine ('2019-11-18', 5343, 695, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,523 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,523 INFO sqlalchemy.engine.base.Engine ('2019-11-19', 5347, 697, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,524 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,524 INFO sqlalchemy.engine.base.Engine ('2019-11-20', 5348, 697, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,525 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,525 INFO sqlalchemy.engine.base.Engine ('2019-11-21', 5351, 700, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,526 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,526 INFO sqlalchemy.engine.base.Engine ('2019-11-22', 5356, 700, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,527 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,527 INFO sqlalchemy.engine.base.Engine ('2019-11-23', 5383, 700, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,528 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,528 INFO sqlalchemy.engine.base.Engine ('2019-11-24', 5409, 704, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,529 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,530 INFO sqlalchemy.engine.base.Engine ('2019-11-25', 5435, 709, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,530 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,531 INFO sqlalchemy.engine.base.Engine ('2019-11-26', 5450, 714, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,531 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,532 INFO sqlalchemy.engine.base.Engine ('2019-11-27', 5479, 714, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,532 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,532 INFO sqlalchemy.engine.base.Engine ('2019-11-28', 5503, 715, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,533 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,533 INFO sqlalchemy.engine.base.Engine ('2019-11-29', 5554, 716, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,534 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,534 INFO sqlalchemy.engine.base.Engine ('2019-11-30', 5643, 718, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,535 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,535 INFO sqlalchemy.engine.base.Engine ('2019-12-01', 5652, 720, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,536 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,536 INFO sqlalchemy.engine.base.Engine ('2019-12-02', 5654, 723, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,537 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,537 INFO sqlalchemy.engine.base.Engine ('2019-12-03', 5678, 723, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,538 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,538 INFO sqlalchemy.engine.base.Engine ('2019-12-04', 5706, 723, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,539 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,539 INFO sqlalchemy.engine.base.Engine ('2019-12-05', 5747, 726, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,540 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,540 INFO sqlalchemy.engine.base.Engine ('2019-12-06', 5802, 728, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,540 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,541 INFO sqlalchemy.engine.base.Engine ('2019-12-07', 5807, 728, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,542 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,542 INFO sqlalchemy.engine.base.Engine ('2019-12-08', 5811, 732, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,543 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,543 INFO sqlalchemy.engine.base.Engine ('2019-12-09', 5811, 732, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,544 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,544 INFO sqlalchemy.engine.base.Engine ('2019-12-10', 5813, 735, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,545 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,545 INFO sqlalchemy.engine.base.Engine ('2019-12-11', 5819, 735, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,546 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,546 INFO sqlalchemy.engine.base.Engine ('2019-12-12', 5825, 737, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,547 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,547 INFO sqlalchemy.engine.base.Engine ('2019-12-13', 5830, 739, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,548 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,548 INFO sqlalchemy.engine.base.Engine ('2019-12-14', 5833, 739, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,549 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,549 INFO sqlalchemy.engine.base.Engine ('2019-12-15', 5837, 740, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,550 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,550 INFO sqlalchemy.engine.base.Engine ('2019-12-16', 5839, 742, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,551 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,551 INFO sqlalchemy.engine.base.Engine ('2019-12-17', 5840, 744, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,552 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,552 INFO sqlalchemy.engine.base.Engine ('2019-12-18', 5846, 745, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,553 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,553 INFO sqlalchemy.engine.base.Engine ('2019-12-19', 5847, 745, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,554 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,554 INFO sqlalchemy.engine.base.Engine ('2019-12-20', 5849, 746, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,555 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,555 INFO sqlalchemy.engine.base.Engine ('2019-12-21', 5850, 746, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,626 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,627 INFO sqlalchemy.engine.base.Engine ('2019-12-22', 5852, 746, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,628 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,628 INFO sqlalchemy.engine.base.Engine ('2019-12-23', 5870, 747, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,629 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,630 INFO sqlalchemy.engine.base.Engine ('2019-12-24', 5878, 748, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,631 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,631 INFO sqlalchemy.engine.base.Engine ('2019-12-25', 5888, 748, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,632 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,632 INFO sqlalchemy.engine.base.Engine ('2019-12-26', 5906, 749, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,632 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,633 INFO sqlalchemy.engine.base.Engine ('2019-12-27', 5927, 749, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,634 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,634 INFO sqlalchemy.engine.base.Engine ('2019-12-28', 5930, 749, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,634 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,635 INFO sqlalchemy.engine.base.Engine ('2019-12-29', 5933, 750, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,635 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,636 INFO sqlalchemy.engine.base.Engine ('2019-12-30', 5936, 752, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,637 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,637 INFO sqlalchemy.engine.base.Engine ('2019-12-31', 5937, 753, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,637 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,638 INFO sqlalchemy.engine.base.Engine ('2020-01-01', 5964, 760, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,638 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,639 INFO sqlalchemy.engine.base.Engine ('2020-01-02', 5989, 764, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,639 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,640 INFO sqlalchemy.engine.base.Engine ('2020-01-03', 5999, 768, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,640 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,641 INFO sqlalchemy.engine.base.Engine ('2020-01-04', 6011, 768, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,641 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,642 INFO sqlalchemy.engine.base.Engine ('2020-01-05', 6023, 771, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,643 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,643 INFO sqlalchemy.engine.base.Engine ('2020-01-06', 6042, 772, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,644 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,645 INFO sqlalchemy.engine.base.Engine ('2020-01-07', 6060, 776, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,646 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,646 INFO sqlalchemy.engine.base.Engine ('2020-01-08', 6089, 778, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,647 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,647 INFO sqlalchemy.engine.base.Engine ('2020-01-09', 6121, 780, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,648 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,649 INFO sqlalchemy.engine.base.Engine ('2020-01-10', 6174, 781, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,649 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,650 INFO sqlalchemy.engine.base.Engine ('2020-01-11', 6178, 782, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,650 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,651 INFO sqlalchemy.engine.base.Engine ('2020-01-12', 6182, 784, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,651 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,652 INFO sqlalchemy.engine.base.Engine ('2020-01-13', 6188, 784, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,652 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,653 INFO sqlalchemy.engine.base.Engine ('2020-01-14', 6191, 788, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,654 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,654 INFO sqlalchemy.engine.base.Engine ('2020-01-15', 6193, 792, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,655 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,655 INFO sqlalchemy.engine.base.Engine ('2020-01-16', 6196, 793, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,656 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,657 INFO sqlalchemy.engine.base.Engine ('2020-01-17', 6201, 793, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,657 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,658 INFO sqlalchemy.engine.base.Engine ('2020-01-18', 6200, 795, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,659 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,660 INFO sqlalchemy.engine.base.Engine ('2020-01-19', 6204, 797, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,661 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,662 INFO sqlalchemy.engine.base.Engine ('2020-01-20', 6206, 801, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,662 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,663 INFO sqlalchemy.engine.base.Engine ('2020-01-21', 6212, 803, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,664 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,665 INFO sqlalchemy.engine.base.Engine ('2020-01-22', 6213, 806, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,666 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,666 INFO sqlalchemy.engine.base.Engine ('2020-01-23', 6215, 808, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,667 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,668 INFO sqlalchemy.engine.base.Engine ('2020-01-24', 6219, 808, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,669 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,669 INFO sqlalchemy.engine.base.Engine ('2020-01-25', 6222, 811, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,670 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,671 INFO sqlalchemy.engine.base.Engine ('2020-01-26', 6223, 811, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,672 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,672 INFO sqlalchemy.engine.base.Engine ('2020-01-27', 6224, 811, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,673 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,674 INFO sqlalchemy.engine.base.Engine ('2020-01-28', 6229, 812, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,675 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,676 INFO sqlalchemy.engine.base.Engine ('2020-01-29', 6248, 812, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,677 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,678 INFO sqlalchemy.engine.base.Engine ('2020-01-30', 6281, 813, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,678 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,679 INFO sqlalchemy.engine.base.Engine ('2020-01-31', 6286, 816, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,680 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,680 INFO sqlalchemy.engine.base.Engine ('2020-02-01', 6291, 820, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,681 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,681 INFO sqlalchemy.engine.base.Engine ('2020-02-02', 6294, 820, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,682 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,683 INFO sqlalchemy.engine.base.Engine ('2020-02-03', 6299, 820, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,683 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,684 INFO sqlalchemy.engine.base.Engine ('2020-02-04', 6310, 821, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,685 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,685 INFO sqlalchemy.engine.base.Engine ('2020-02-05', 6319, 824, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,686 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,687 INFO sqlalchemy.engine.base.Engine ('2020-02-06', 6337, 827, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,687 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,688 INFO sqlalchemy.engine.base.Engine ('2020-02-07', 6352, 829, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,689 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,690 INFO sqlalchemy.engine.base.Engine ('2020-02-08', 6353, 833, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,691 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,691 INFO sqlalchemy.engine.base.Engine ('2020-02-09', 6356, 834, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,693 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,693 INFO sqlalchemy.engine.base.Engine ('2020-02-10', 6359, 836, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,695 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,695 INFO sqlalchemy.engine.base.Engine ('2020-02-11', 6361, 843, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,697 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,698 INFO sqlalchemy.engine.base.Engine ('2020-02-12', 6366, 845, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,698 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,699 INFO sqlalchemy.engine.base.Engine ('2020-02-13', 6370, 848, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,700 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,700 INFO sqlalchemy.engine.base.Engine ('2020-02-14', 6387, 852, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,701 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,702 INFO sqlalchemy.engine.base.Engine ('2020-02-15', 6399, 854, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,702 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,703 INFO sqlalchemy.engine.base.Engine ('2020-02-16', 6399, 854, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,703 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,704 INFO sqlalchemy.engine.base.Engine ('2020-02-17', 6407, 857, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,705 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,705 INFO sqlalchemy.engine.base.Engine ('2020-02-18', 6411, 860, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,706 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,706 INFO sqlalchemy.engine.base.Engine ('2020-02-19', 6412, 861, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,707 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,708 INFO sqlalchemy.engine.base.Engine ('2020-02-20', 6413, 861, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,710 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,711 INFO sqlalchemy.engine.base.Engine ('2020-02-21', 6428, 862, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,712 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,712 INFO sqlalchemy.engine.base.Engine ('2020-02-22', 6436, 862, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,713 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,714 INFO sqlalchemy.engine.base.Engine ('2020-02-23', 6439, 867, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,715 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,716 INFO sqlalchemy.engine.base.Engine ('2020-02-24', 6442, 868, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,717 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,718 INFO sqlalchemy.engine.base.Engine ('2020-02-25', 6455, 869, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,718 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,719 INFO sqlalchemy.engine.base.Engine ('2020-02-26', 6460, 871, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,720 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,720 INFO sqlalchemy.engine.base.Engine ('2020-02-27', 6470, 872, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,721 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,722 INFO sqlalchemy.engine.base.Engine ('2020-02-28', 6482, 873, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,722 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,723 INFO sqlalchemy.engine.base.Engine ('2020-02-29', 6495, 876, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,724 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,724 INFO sqlalchemy.engine.base.Engine ('2020-03-01', 6500, 876, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,725 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,726 INFO sqlalchemy.engine.base.Engine ('2020-03-02', 6504, 878, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,727 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,728 INFO sqlalchemy.engine.base.Engine ('2020-03-03', 6510, 885, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,729 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,730 INFO sqlalchemy.engine.base.Engine ('2020-03-04', 6519, 890, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,731 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,731 INFO sqlalchemy.engine.base.Engine ('2020-03-05', 6527, 893, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,732 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,733 INFO sqlalchemy.engine.base.Engine ('2020-03-06', 6534, 894, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,734 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,734 INFO sqlalchemy.engine.base.Engine ('2020-03-07', 6539, 894, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,735 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,736 INFO sqlalchemy.engine.base.Engine ('2020-03-08', 6549, 897, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,737 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,738 INFO sqlalchemy.engine.base.Engine ('2020-03-09', 6568, 897, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,738 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,739 INFO sqlalchemy.engine.base.Engine ('2020-03-10', 6590, 902, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,739 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,740 INFO sqlalchemy.engine.base.Engine ('2020-03-11', 6609, 906, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,741 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,742 INFO sqlalchemy.engine.base.Engine ('2020-03-12', 6636, 909, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,743 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,744 INFO sqlalchemy.engine.base.Engine ('2020-03-13', 6640, 909, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,745 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,745 INFO sqlalchemy.engine.base.Engine ('2020-03-14', 6645, 911, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,746 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,747 INFO sqlalchemy.engine.base.Engine ('2020-03-15', 6649, 916, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,748 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,748 INFO sqlalchemy.engine.base.Engine ('2020-03-16', 6652, 920, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,749 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,750 INFO sqlalchemy.engine.base.Engine ('2020-03-17', 6672, 922, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,751 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,752 INFO sqlalchemy.engine.base.Engine ('2020-03-18', 6687, 926, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,752 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,753 INFO sqlalchemy.engine.base.Engine ('2020-03-19', 6707, 928, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,754 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,754 INFO sqlalchemy.engine.base.Engine ('2020-03-20', 6729, 933, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,755 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,755 INFO sqlalchemy.engine.base.Engine ('2020-03-21', 6764, 934, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,756 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,757 INFO sqlalchemy.engine.base.Engine ('2020-03-22', 6771, 939, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,758 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,758 INFO sqlalchemy.engine.base.Engine ('2020-03-23', 6776, 943, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,760 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,761 INFO sqlalchemy.engine.base.Engine ('2020-03-24', 6783, 948, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,762 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,763 INFO sqlalchemy.engine.base.Engine ('2020-03-25', 6785, 950, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,764 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,764 INFO sqlalchemy.engine.base.Engine ('2020-03-26', 6790, 951, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,765 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,766 INFO sqlalchemy.engine.base.Engine ('2020-03-27', 6792, 952, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,767 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,768 INFO sqlalchemy.engine.base.Engine ('2020-03-28', 6798, 953, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,769 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,769 INFO sqlalchemy.engine.base.Engine ('2020-03-29', 6805, 957, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,770 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,771 INFO sqlalchemy.engine.base.Engine ('2020-03-30', 6809, 958, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,771 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,772 INFO sqlalchemy.engine.base.Engine ('2020-03-31', 6832, 963, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,772 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,773 INFO sqlalchemy.engine.base.Engine ('2020-04-01', 6867, 968, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,774 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,774 INFO sqlalchemy.engine.base.Engine ('2020-04-02', 6868, 974, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,776 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,777 INFO sqlalchemy.engine.base.Engine ('2020-04-03', 6877, 977, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,778 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,778 INFO sqlalchemy.engine.base.Engine ('2020-04-04', 6882, 979, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,779 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,780 INFO sqlalchemy.engine.base.Engine ('2020-04-05', 6886, 979, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,781 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,782 INFO sqlalchemy.engine.base.Engine ('2020-04-06', 6892, 982, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,782 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,783 INFO sqlalchemy.engine.base.Engine ('2020-04-07', 6912, 987, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,784 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,784 INFO sqlalchemy.engine.base.Engine ('2020-04-08', 6913, 991, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,785 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,786 INFO sqlalchemy.engine.base.Engine ('2020-04-09', 6921, 993, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,786 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,787 INFO sqlalchemy.engine.base.Engine ('2020-04-10', 6927, 995, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,787 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,788 INFO sqlalchemy.engine.base.Engine ('2020-04-11', 6938, 996, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,789 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,789 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,790 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,791 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,792 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,792 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,793 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,794 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,795 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,795 INFO sqlalchemy.engine.base.Engine ('2020-04-12', 6941, 998, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,796 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,797 INFO sqlalchemy.engine.base.Engine ('2020-04-13', 6948, 1002, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,798 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,798 INFO sqlalchemy.engine.base.Engine ('2020-04-14', 6956, 1006, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,799 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,799 INFO sqlalchemy.engine.base.Engine ('2020-04-15', 6982, 1007, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,800 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,801 INFO sqlalchemy.engine.base.Engine ('2020-04-16', 7003, 1007, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,801 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,802 INFO sqlalchemy.engine.base.Engine ('2020-04-17', 7024, 1012, '2020-12-02 17:51:17.437401')

2020-12-02 18:07:03,803 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,803 INFO sqlalchemy.engine.base.Engine ('2020-04-18', 7050, 1016, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,804 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,804 INFO sqlalchemy.engine.base.Engine ('2020-04-19', 7092, 1017, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,805 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,806 INFO sqlalchemy.engine.base.Engine ('2020-04-20', 7154, 1021, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,885 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,885 INFO sqlalchemy.engine.base.Engine ('2020-04-21', 7233, 1028, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,886 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,886 INFO sqlalchemy.engine.base.Engine ('2020-04-22', 7245, 1031, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,887 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,887 INFO sqlalchemy.engine.base.Engine ('2020-04-23', 7257, 1033, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,888 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,888 INFO sqlalchemy.engine.base.Engine ('2020-04-24', 7265, 1045, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,889 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,889 INFO sqlalchemy.engine.base.Engine ('2020-04-25', 7269, 1048, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,889 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,890 INFO sqlalchemy.engine.base.Engine ('2020-04-26', 7276, 1053, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,890 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,891 INFO sqlalchemy.engine.base.Engine ('2020-04-27', 7281, 1055, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,891 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,892 INFO sqlalchemy.engine.base.Engine ('2020-04-28', 7290, 1059, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,893 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,893 INFO sqlalchemy.engine.base.Engine ('2020-04-29', 7298, 1063, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,894 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,895 INFO sqlalchemy.engine.base.Engine ('2020-04-30', 7353, 1064, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,895 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,896 INFO sqlalchemy.engine.base.Engine ('2020-05-01', 7404, 1069, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,896 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,897 INFO sqlalchemy.engine.base.Engine ('2020-05-02', 7411, 1073, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,897 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,897 INFO sqlalchemy.engine.base.Engine ('2020-05-03', 7423, 1076, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,898 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,898 INFO sqlalchemy.engine.base.Engine ('2020-05-04', 7429, 1080, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,899 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,900 INFO sqlalchemy.engine.base.Engine ('2020-05-05', 7439, 1088, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,900 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,900 INFO sqlalchemy.engine.base.Engine ('2020-05-06', 7487, 1094, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,901 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,901 INFO sqlalchemy.engine.base.Engine ('2020-05-07', 7516, 1105, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,902 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,902 INFO sqlalchemy.engine.base.Engine ('2020-05-08', 7532, 1113, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,903 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,903 INFO sqlalchemy.engine.base.Engine ('2020-05-09', 7557, 1120, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,904 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,904 INFO sqlalchemy.engine.base.Engine ('2020-05-10', 7593, 1126, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,905 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,905 INFO sqlalchemy.engine.base.Engine ('2020-05-11', 7634, 1129, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,906 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,906 INFO sqlalchemy.engine.base.Engine ('2020-05-12', 7664, 1147, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,907 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,907 INFO sqlalchemy.engine.base.Engine ('2020-05-13', 7702, 1154, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,908 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,909 INFO sqlalchemy.engine.base.Engine ('2020-05-14', 7758, 1156, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,910 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,910 INFO sqlalchemy.engine.base.Engine ('2020-05-15', 7823, 1161, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,911 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,912 INFO sqlalchemy.engine.base.Engine ('2020-05-16', 7826, 1167, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,912 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,913 INFO sqlalchemy.engine.base.Engine ('2020-05-17', 7827, 1172, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,913 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,914 INFO sqlalchemy.engine.base.Engine ('2020-05-18', 7831, 1179, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,914 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,915 INFO sqlalchemy.engine.base.Engine ('2020-05-19', 7841, 1180, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,915 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-12-02 18:07:03,916 INFO sqlalchemy.engine.base.Engine ('2020-05-20', 7842, 1187, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,916 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,917 INFO sqlalchemy.engine.base.Engine ('2020-05-21', 7845, 1189, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,917 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,918 INFO sqlalchemy.engine.base.Engine ('2020-05-22', 7854, 1191, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,918 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,919 INFO sqlalchemy.engine.base.Engine ('2020-05-23', 7861, 1195, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,919 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,919 INFO sqlalchemy.engine.base.Engine ('2020-05-24', 7870, 1200, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,920 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,920 INFO sqlalchemy.engine.base.Engine ('2020-05-25', 7876, 1205, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,921 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,921 INFO sqlalchemy.engine.base.Engine ('2020-05-26', 7884, 1208, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,922 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,922 INFO sqlalchemy.engine.base.Engine ('2020-05-27', 7928, 1212, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,923 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,923 INFO sqlalchemy.engine.base.Engine ('2020-05-28', 7961, 1214, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,924 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,924 INFO sqlalchemy.engine.base.Engine ('2020-05-29', 7969, 1216, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,925 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,925 INFO sqlalchemy.engine.base.Engine ('2020-05-30', 7978, 1219, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,926 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,926 INFO sqlalchemy.engine.base.Engine ('2020-05-31', 7979, 1220, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,927 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,928 INFO sqlalchemy.engine.base.Engine ('2020-06-01', 7979, 1222, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,928 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,929 INFO sqlalchemy.engine.base.Engine ('2020-06-02', 7999, 1226, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,929 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,930 INFO sqlalchemy.engine.base.Engine ('2020-06-03', 8018, 1229, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,930 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,931 INFO sqlalchemy.engine.base.Engine ('2020-06-04', 8040, 1229, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,931 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,932 INFO sqlalchemy.engine.base.Engine ('2020-06-05', 8069, 1238, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,932 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,933 INFO sqlalchemy.engine.base.Engine ('2020-06-06', 8075, 1240, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,933 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,934 INFO sqlalchemy.engine.base.Engine ('2020-06-07', 8080, 1241, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,934 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,935 INFO sqlalchemy.engine.base.Engine ('2020-06-08', 8083, 1246, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,935 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,935 INFO sqlalchemy.engine.base.Engine ('2020-06-09', 8096, 1250, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,936 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,936 INFO sqlalchemy.engine.base.Engine ('2020-06-10', 8104, 1255, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,937 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,937 INFO sqlalchemy.engine.base.Engine ('2020-06-11', 8109, 1260, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,938 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,938 INFO sqlalchemy.engine.base.Engine ('2020-06-12', 8116, 1264, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,939 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,939 INFO sqlalchemy.engine.base.Engine ('2020-06-13', 8143, 1265, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,939 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,940 INFO sqlalchemy.engine.base.Engine ('2020-06-14', 8169, 1269, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,940 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,941 INFO sqlalchemy.engine.base.Engine ('2020-06-15', 8196, 1276, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,942 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,942 INFO sqlalchemy.engine.base.Engine ('2020-06-16', 8201, 1280, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,943 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,943 INFO sqlalchemy.engine.base.Engine ('2020-06-17', 8206, 1283, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,944 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,944 INFO sqlalchemy.engine.base.Engine ('2020-06-18', 8212, 1284, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,945 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,945 INFO sqlalchemy.engine.base.Engine ('2020-06-19', 8217, 1286, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,946 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,947 INFO sqlalchemy.engine.base.Engine ('2020-06-20', 8222, 1289, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,947 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,947 INFO sqlalchemy.engine.base.Engine ('2020-06-21', 8230, 1291, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,948 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-12-02 18:07:03,948 INFO sqlalchemy.engine.base.Engine ('2020-06-22', 8234, 1295, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,949 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,949 INFO sqlalchemy.engine.base.Engine ('2020-06-23', 8241, 1298, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,950 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,950 INFO sqlalchemy.engine.base.Engine ('2020-06-24', 8246, 1301, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,951 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,951 INFO sqlalchemy.engine.base.Engine ('2020-06-25', 8255, 1305, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,952 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,952 INFO sqlalchemy.engine.base.Engine ('2020-06-26', 8279, 1306, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,953 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,953 INFO sqlalchemy.engine.base.Engine ('2020-06-27', 8304, 1308, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,954 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,954 INFO sqlalchemy.engine.base.Engine ('2020-06-28', 8308, 1311, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,955 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,955 INFO sqlalchemy.engine.base.Engine ('2020-06-29', 8312, 1312, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,956 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,956 INFO sqlalchemy.engine.base.Engine ('2020-06-30', 8318, 1317, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,957 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,957 INFO sqlalchemy.engine.base.Engine ('2020-07-01', 8325, 1320, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,958 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,958 INFO sqlalchemy.engine.base.Engine ('2020-07-02', 8340, 1323, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,959 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,959 INFO sqlalchemy.engine.base.Engine ('2020-07-03', 8347, 1323, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,960 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,961 INFO sqlalchemy.engine.base.Engine ('2020-07-04', 8358, 1330, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,961 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,962 INFO sqlalchemy.engine.base.Engine ('2020-07-05', 8368, 1331, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,962 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,963 INFO sqlalchemy.engine.base.Engine ('2020-07-06', 8376, 1334, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,963 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,963 INFO sqlalchemy.engine.base.Engine ('2020-07-07', 8392, 1336, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,964 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,965 INFO sqlalchemy.engine.base.Engine ('2020-07-08', 8414, 1339, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,965 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,965 INFO sqlalchemy.engine.base.Engine ('2020-07-09', 8437, 1340, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,966 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,966 INFO sqlalchemy.engine.base.Engine ('2020-07-10', 8468, 1342, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,967 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,967 INFO sqlalchemy.engine.base.Engine ('2020-07-11', 8473, 1344, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,968 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,968 INFO sqlalchemy.engine.base.Engine ('2020-07-12', 8475, 1348, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,969 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,969 INFO sqlalchemy.engine.base.Engine ('2020-07-13', 8482, 1350, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,970 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,970 INFO sqlalchemy.engine.base.Engine ('2020-07-14', 8485, 1354, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,970 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,971 INFO sqlalchemy.engine.base.Engine ('2020-07-15', 8500, 1358, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,971 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,972 INFO sqlalchemy.engine.base.Engine ('2020-07-16', 8517, 1358, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,973 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,973 INFO sqlalchemy.engine.base.Engine ('2020-07-17', 8536, 1359, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,973 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,974 INFO sqlalchemy.engine.base.Engine ('2020-07-18', 8539, 1359, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,974 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,975 INFO sqlalchemy.engine.base.Engine ('2020-07-19', 8540, 1363, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,976 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,976 INFO sqlalchemy.engine.base.Engine ('2020-07-20', 8545, 1363, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,977 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,977 INFO sqlalchemy.engine.base.Engine ('2020-07-21', 8551, 1365, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,978 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,979 INFO sqlalchemy.engine.base.Engine ('2020-07-22', 8553, 1369, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,979 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,980 INFO sqlalchemy.engine.base.Engine ('2020-07-23', 8556, 1371, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,980 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,981 INFO sqlalchemy.engine.base.Engine ('2020-07-24', 8564, 1374, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,981 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-12-02 18:07:03,981 INFO sqlalchemy.engine.base.Engine ('2020-07-25', 8572, 1376, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,982 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,982 INFO sqlalchemy.engine.base.Engine ('2020-07-26', 8574, 1382, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,983 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,983 INFO sqlalchemy.engine.base.Engine ('2020-07-27', 8583, 1386, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,984 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,984 INFO sqlalchemy.engine.base.Engine ('2020-07-28', 8601, 1389, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,985 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,985 INFO sqlalchemy.engine.base.Engine ('2020-07-29', 8614, 1391, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,986 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,986 INFO sqlalchemy.engine.base.Engine ('2020-07-30', 8625, 1393, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,987 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,987 INFO sqlalchemy.engine.base.Engine ('2020-07-31', 8642, 1394, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,988 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,988 INFO sqlalchemy.engine.base.Engine ('2020-08-01', 8657, 1394, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,988 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,989 INFO sqlalchemy.engine.base.Engine ('2020-08-02', 8662, 1396, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,989 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,990 INFO sqlalchemy.engine.base.Engine ('2020-08-03', 8665, 1399, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,990 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,991 INFO sqlalchemy.engine.base.Engine ('2020-08-04', 8669, 1402, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,991 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,992 INFO sqlalchemy.engine.base.Engine ('2020-08-05', 8671, 1403, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,993 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,993 INFO sqlalchemy.engine.base.Engine ('2020-08-06', 8680, 1403, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,994 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,994 INFO sqlalchemy.engine.base.Engine ('2020-08-07', 8690, 1403, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,995 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,995 INFO sqlalchemy.engine.base.Engine ('2020-08-08', 8694, 1404, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,996 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,996 INFO sqlalchemy.engine.base.Engine ('2020-08-09', 8696, 1405, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,997 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,997 INFO sqlalchemy.engine.base.Engine ('2020-08-10', 8697, 1408, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,998 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,998 INFO sqlalchemy.engine.base.Engine ('2020-08-11', 8704, 1409, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:03,999 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:03,999 INFO sqlalchemy.engine.base.Engine ('2020-08-12', 8705, 1411, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,000 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,000 INFO sqlalchemy.engine.base.Engine ('2020-08-13', 8707, 1416, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,001 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,001 INFO sqlalchemy.engine.base.Engine ('2020-08-14', 8710, 1420, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,002 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,002 INFO sqlalchemy.engine.base.Engine ('2020-08-15', 8714, 1420, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,003 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,003 INFO sqlalchemy.engine.base.Engine ('2020-08-16', 8723, 1420, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,004 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,004 INFO sqlalchemy.engine.base.Engine ('2020-08-17', 8725, 1421, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,005 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,005 INFO sqlalchemy.engine.base.Engine ('2020-08-18', 8731, 1421, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,006 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,006 INFO sqlalchemy.engine.base.Engine ('2020-08-19', 8749, 1424, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,007 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,007 INFO sqlalchemy.engine.base.Engine ('2020-08-20', 8767, 1424, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,008 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,008 INFO sqlalchemy.engine.base.Engine ('2020-08-21', 8784, 1426, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,009 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,010 INFO sqlalchemy.engine.base.Engine ('2020-08-22', 8793, 1426, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,010 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,011 INFO sqlalchemy.engine.base.Engine ('2020-08-23', 8808, 1426, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,095 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,095 INFO sqlalchemy.engine.base.Engine ('2020-08-24', 8825, 1429, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,096 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,096 INFO sqlalchemy.engine.base.Engine ('2020-08-25', 8835, 1439, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,097 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,097 INFO sqlalchemy.engine.base.Engine ('2020-08-26', 8857, 1443, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,098 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-12-02 18:07:04,098 INFO sqlalchemy.engine.base.Engine ('2020-08-27', 8883, 1444, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,099 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,099 INFO sqlalchemy.engine.base.Engine ('2020-08-28', 8916, 1445, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,100 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,100 INFO sqlalchemy.engine.base.Engine ('2020-08-29', 8922, 1447, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,101 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,101 INFO sqlalchemy.engine.base.Engine ('2020-08-30', 8925, 1450, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,102 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,102 INFO sqlalchemy.engine.base.Engine ('2020-08-31', 8928, 1451, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,102 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,103 INFO sqlalchemy.engine.base.Engine ('2020-09-01', 8932, 1457, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,104 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,104 INFO sqlalchemy.engine.base.Engine ('2020-09-02', 8939, 1459, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,105 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,105 INFO sqlalchemy.engine.base.Engine ('2020-09-03', 8940, 1460, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,105 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,106 INFO sqlalchemy.engine.base.Engine ('2020-09-04', 8956, 1460, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,106 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,107 INFO sqlalchemy.engine.base.Engine ('2020-09-05', 8966, 1460, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,107 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,108 INFO sqlalchemy.engine.base.Engine ('2020-09-06', 8972, 1461, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,108 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,109 INFO sqlalchemy.engine.base.Engine ('2020-09-07', 8978, 1465, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,110 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,111 INFO sqlalchemy.engine.base.Engine ('2020-09-09', 8986, 1467, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,112 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,113 INFO sqlalchemy.engine.base.Engine ('2020-09-10', 8989, 1470, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,113 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,114 INFO sqlalchemy.engine.base.Engine ('2020-09-11', 8991, 1471, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,115 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,115 INFO sqlalchemy.engine.base.Engine ('2020-09-12', 8995, 1473, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,115 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,116 INFO sqlalchemy.engine.base.Engine ('2020-09-13', 9000, 1474, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,116 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,117 INFO sqlalchemy.engine.base.Engine ('2020-09-14', 9002, 1476, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,117 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,118 INFO sqlalchemy.engine.base.Engine ('2020-09-15', 9022, 1477, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,118 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,119 INFO sqlalchemy.engine.base.Engine ('2020-09-16', 9030, 1478, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,120 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,120 INFO sqlalchemy.engine.base.Engine ('2020-09-16', 9030, 1478, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,121 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,121 INFO sqlalchemy.engine.base.Engine ('2020-09-16', 9030, 1478, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,122 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,122 INFO sqlalchemy.engine.base.Engine ('2020-09-16', 9030, 1478, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,123 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,123 INFO sqlalchemy.engine.base.Engine ('2020-09-16', 9030, 1478, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,124 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,125 INFO sqlalchemy.engine.base.Engine ('2020-09-17', 9044, 1481, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,126 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,126 INFO sqlalchemy.engine.base.Engine ('2020-09-18', 9059, 1484, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,127 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,128 INFO sqlalchemy.engine.base.Engine ('2020-09-19', 9062, 1486, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,129 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,129 INFO sqlalchemy.engine.base.Engine ('2020-09-20', 9063, 1489, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,130 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,131 INFO sqlalchemy.engine.base.Engine ('2020-09-21', 9065, 1492, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,132 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,132 INFO sqlalchemy.engine.base.Engine ('2020-09-22', 9066, 1494, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,133 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,133 INFO sqlalchemy.engine.base.Engine ('2020-09-23', 9068, 1495, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,134 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,135 INFO sqlalchemy.engine.base.Engine ('2020-09-24', 9073, 1495, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,135 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,136 INFO sqlalchemy.engine.base.Engine ('2020-09-25', 9076, 1495, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,137 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-12-02 18:07:04,137 INFO sqlalchemy.engine.base.Engine ('2020-09-26', 9079, 1499, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,138 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,138 INFO sqlalchemy.engine.base.Engine ('2020-09-27', 9085, 1501, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,139 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,139 INFO sqlalchemy.engine.base.Engine ('2020-09-28', 9089, 1501, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,140 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,140 INFO sqlalchemy.engine.base.Engine ('2020-09-29', 9100, 1502, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,141 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,142 INFO sqlalchemy.engine.base.Engine ('2020-09-30', 9111, 1505, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,143 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,143 INFO sqlalchemy.engine.base.Engine ('2020-10-01', 9127, 1507, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,144 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,145 INFO sqlalchemy.engine.base.Engine ('2020-10-02', 9140, 1515, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,146 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,146 INFO sqlalchemy.engine.base.Engine ('2020-10-03', 9142, 1516, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,147 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,148 INFO sqlalchemy.engine.base.Engine ('2020-10-04', 9151, 1517, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,148 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,149 INFO sqlalchemy.engine.base.Engine ('2020-10-05', 9156, 1518, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,150 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,150 INFO sqlalchemy.engine.base.Engine ('2020-10-06', 9170, 1519, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,151 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,151 INFO sqlalchemy.engine.base.Engine ('2020-10-07', 9190, 1521, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,152 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,153 INFO sqlalchemy.engine.base.Engine ('2020-10-08', 9194, 1522, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,153 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,154 INFO sqlalchemy.engine.base.Engine ('2020-10-09', 9197, 1526, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,155 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,155 INFO sqlalchemy.engine.base.Engine ('2020-10-10', 9200, 1526, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,156 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,156 INFO sqlalchemy.engine.base.Engine ('2020-10-11', 9204, 1528, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,157 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,157 INFO sqlalchemy.engine.base.Engine ('2020-10-12', 9214, 1531, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,159 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,159 INFO sqlalchemy.engine.base.Engine ('2020-10-13', 9220, 1536, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,160 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,161 INFO sqlalchemy.engine.base.Engine ('2020-10-14', 9248, 1540, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,162 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,162 INFO sqlalchemy.engine.base.Engine ('2020-10-15', 9265, 1540, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,163 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,164 INFO sqlalchemy.engine.base.Engine ('2020-10-16', 9297, 1542, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,164 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,165 INFO sqlalchemy.engine.base.Engine ('2020-10-17', 9300, 1546, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,166 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,166 INFO sqlalchemy.engine.base.Engine ('2020-10-18', 9308, 1547, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,167 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,167 INFO sqlalchemy.engine.base.Engine ('2020-10-19', 9314, 1549, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,168 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,169 INFO sqlalchemy.engine.base.Engine ('2020-10-20', 9322, 1552, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,169 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,170 INFO sqlalchemy.engine.base.Engine ('2020-10-21', 9335, 1554, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,171 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,171 INFO sqlalchemy.engine.base.Engine ('2020-10-22', 9353, 1556, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,172 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,172 INFO sqlalchemy.engine.base.Engine ('2020-10-23', 9362, 1560, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,173 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,173 INFO sqlalchemy.engine.base.Engine ('2020-10-24', 9363, 1563, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,174 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,175 INFO sqlalchemy.engine.base.Engine ('2020-10-25', 9371, 1563, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,176 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,176 INFO sqlalchemy.engine.base.Engine ('2020-10-26', 9378, 1565, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,177 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,178 INFO sqlalchemy.engine.base.Engine ('2020-10-27', 9395, 1566, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,179 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,179 INFO sqlalchemy.engine.base.Engine ('2020-10-28', 9417, 1567, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,180 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)

2020-12-02 18:07:04,180 INFO sqlalchemy.engine.base.Engine ('2020-10-29', 9437, 1569, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,181 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,182 INFO sqlalchemy.engine.base.Engine ('2020-10-30', 9457, 1571, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,182 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,183 INFO sqlalchemy.engine.base.Engine ('2020-10-31', 9462, 1575, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,184 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,184 INFO sqlalchemy.engine.base.Engine ('2020-11-01', 9465, 1576, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,185 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,186 INFO sqlalchemy.engine.base.Engine ('2020-11-02', 9465, 1578, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,186 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,187 INFO sqlalchemy.engine.base.Engine ('2020-11-03', 9469, 1578, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,188 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,188 INFO sqlalchemy.engine.base.Engine ('2020-11-04', 9476, 1579, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,189 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,189 INFO sqlalchemy.engine.base.Engine ('2020-11-05', 9481, 1581, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,190 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,190 INFO sqlalchemy.engine.base.Engine ('2020-11-06', 9484, 1587, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,191 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,192 INFO sqlalchemy.engine.base.Engine ('2020-11-07', 9491, 1589, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,193 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,193 INFO sqlalchemy.engine.base.Engine ('2020-11-08', 9493, 1592, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,194 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,195 INFO sqlalchemy.engine.base.Engine ('2020-11-09', 9497, 1593, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,196 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,196 INFO sqlalchemy.engine.base.Engine ('2020-11-10', 9501, 1594, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,197 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,198 INFO sqlalchemy.engine.base.Engine ('2020-11-11', 9507, 1595, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,198 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,199 INFO sqlalchemy.engine.base.Engine ('2020-11-12', 9544, 1597, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,200 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,200 INFO sqlalchemy.engine.base.Engine ('2020-11-13', 9551, 1599, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,201 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,201 INFO sqlalchemy.engine.base.Engine ('2020-11-14', 9556, 1603, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,202 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,203 INFO sqlalchemy.engine.base.Engine ('2020-11-15', 9563, 1605, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,203 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,204 INFO sqlalchemy.engine.base.Engine ('2020-11-16', 9565, 1606, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,205 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,205 INFO sqlalchemy.engine.base.Engine ('2020-11-17', 9569, 1608, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,206 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,206 INFO sqlalchemy.engine.base.Engine ('2020-11-18', 9581, 1613, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,207 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,208 INFO sqlalchemy.engine.base.Engine ('2020-11-19', 9583, 1613, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,209 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,210 INFO sqlalchemy.engine.base.Engine ('2020-11-20', 9585, 1614, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,211 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,212 INFO sqlalchemy.engine.base.Engine ('2020-11-21', 9611, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,213 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,213 INFO sqlalchemy.engine.base.Engine ('2020-11-22', 9647, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,214 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,215 INFO sqlalchemy.engine.base.Engine ('2020-11-23', 9681, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,215 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,216 INFO sqlalchemy.engine.base.Engine ('2020-11-24', 9708, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,217 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,217 INFO sqlalchemy.engine.base.Engine ('2020-11-25', 9733, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,218 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,218 INFO sqlalchemy.engine.base.Engine ('2020-11-26', 9769, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,219 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,220 INFO sqlalchemy.engine.base.Engine ('2020-11-27', 9838, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,220 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,221 INFO sqlalchemy.engine.base.Engine ('2020-11-28', 9926, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,222 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,222 INFO sqlalchemy.engine.base.Engine ('2020-11-29', 9932, 1618, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,223 INFO sqlalchemy.engine.base.Engine INSERT INTO data (date, subscribers, reviews, timestamp) VALUES (?, ?, ?, ?)
2020-12-02 18:07:04,223 INFO sqlalchemy.engine.base.Engine ('2020-12-02', 10003, 1658, '2020-12-02 17:51:17.437401')
2020-12-02 18:07:04,233 INFO sqlalchemy.engine.base.Engine COMMIT

In [ ]:
def read_data():
    from assets import models
    df= pd.read_csv('assets/data.csv')
    for index,_df in df.iterrows():
        date=datetime.datetime.strptime(_df['date'],'%Y/%m/%d').date()
        row=models.Data(date=date,subscribers=_df['subscribers'],reviews=_df['reviews'])
        db_session.add(row)
    db_session.commit()